### ISSUE TITLE
One module per controller.

### ISSUE THREAD

**Issue by yantrab** [jnwltr/swagger-angular-generator#58]
If i have 2 routes , in one controller, it is generate 2 modules for each route (in the store). 
for example i have authCntl that have login and logout routes.
i expect that i get one module  that have all auth functions.

**Comment by jnwltr** [comment]
I think your proposal could be better. @fazpu, @sangecz, do you see any drawbacks?

**Comment by fazpu** [comment]
The generated ngrx files (actions, effects, reducers) are generated per endpoint and thus, the modules are per endpoint as well.

I believe this is the correct way.
Imagine you don't want to have the ngrx logic for login endpoint in the production-built js files, because you want to handle saving token in effect upon successful login and hence, you need to write your own implementation.

In the current setup, you import only the logout module and you write the login on your own (only using the generated controller and interfaces)

If both login and logout ngrx files were under one module, you would have unnecessary code in your production files.
